=begin
#Tiketeo API

#Autenticación: Bearer <secret_key> 

The version of the OpenAPI document: v1
Contact: romario.lopez@tiketeo.mx
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::TicketsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TicketsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::TicketsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TicketsApi' do
    it 'should create an instance of TicketsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::TicketsApi)
    end
  end

  # unit tests for create_ticket
  # Create Ticket
  # Crea un ticket de lotería utilizando el número del cliente. En &#x60;external_id&#x60; puedes agregar un ID interno (como número de ticket); ésta información será devuelta al checar si un ticket es ganador.
  # @param [Hash] opts the optional parameters
  # @option opts [Body1] :body1 
  # @return [InlineResponse2011]
  describe 'create_ticket test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
