=begin
#Tiketeo API

#Autenticación: Bearer <secret_key> 

The version of the OpenAPI document: v1
Contact: romario.lopez@tiketeo.mx
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::WinnersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'WinnersApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::WinnersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WinnersApi' do
    it 'should create an instance of WinnersApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::WinnersApi)
    end
  end

  # unit tests for check_winner
  # Check Winner
  # Obtiene la información de un ganaddor
  # @param [Hash] opts the optional parameters
  # @option opts [Body2] :body2 
  # @return [InlineResponse2001]
  describe 'check_winner test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for claim_winner
  # Claim Winner
  # Confirma que un ganador haya obtenido su premio
  # @param winner_id El ID del ganador obtenido en &#x60;/winners/check&#x60;
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2001]
  describe 'claim_winner test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
