=begin
#Tiketeo API

#Autenticación: Bearer <secret_key> 

The version of the OpenAPI document: v1
Contact: romario.lopez@tiketeo.mx
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/body'
require 'openapi_client/models/body1'
require 'openapi_client/models/body2'
require 'openapi_client/models/error'
require 'openapi_client/models/error_errors'
require 'openapi_client/models/inline_response200'
require 'openapi_client/models/inline_response2001'
require 'openapi_client/models/inline_response201'
require 'openapi_client/models/inline_response2011'
require 'openapi_client/models/inline_response2011_data'
require 'openapi_client/models/request_body_errors'
require 'openapi_client/models/tickets_ticket'
require 'openapi_client/models/topup'
require 'openapi_client/models/topup_biller'
require 'openapi_client/models/topups_topup'
require 'openapi_client/models/winner'
require 'openapi_client/models/winner_prize'
require 'openapi_client/models/winner_ticket'
require 'openapi_client/models/winnerscheck_winner'

# APIs
require 'openapi_client/api/tickets_api'
require 'openapi_client/api/topups_api'
require 'openapi_client/api/winners_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
