=begin
#Tiketeo API

#Autenticación: Bearer <secret_key> 

The version of the OpenAPI document: v1
Contact: romario.lopez@tiketeo.mx
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

require 'cgi'

module OpenapiClient
  class TicketsApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Create Ticket
    # Crea un ticket de lotería utilizando el número del cliente. En `external_id` puedes agregar un ID interno (como número de ticket); ésta información será devuelta al checar si un ticket es ganador.
    # @param [Hash] opts the optional parameters
    # @option opts [Body1] :body1 
    # @return [InlineResponse2011]
    def create_ticket(opts = {})
      data, _status_code, _headers = create_ticket_with_http_info(opts)
      data
    end

    # Create Ticket
    # Crea un ticket de lotería utilizando el número del cliente. En &#x60;external_id&#x60; puedes agregar un ID interno (como número de ticket); ésta información será devuelta al checar si un ticket es ganador.
    # @param [Hash] opts the optional parameters
    # @option opts [Body1] :body1 
    # @return [Array<(InlineResponse2011, Integer, Hash)>] InlineResponse2011 data, response status code and response headers
    def create_ticket_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: TicketsApi.create_ticket ...'
      end
      # resource path
      local_var_path = '/tickets'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(opts[:'body1'])

      # return_type
      return_type = opts[:debug_return_type] || 'InlineResponse2011'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['BearerAuth']

      new_options = opts.merge(
        :operation => :"TicketsApi.create_ticket",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TicketsApi#create_ticket\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
